Repository node-saml/node-saml, pull requests merged in 2022-08, with the labels that each got.

#141 Improve tests
  .eslintrc.json
  package-lock.json
  package.json
  test/samlTests.spec.ts
  test/tests.spec.ts
  tsconfig.eslint.json
Labels: chore

#147 Consolidate all SAML class code to single file
  src/saml.ts
  src/saml/generate.ts
  src/saml/process.ts
Labels: chore

#143 Include AuthnRequestsSigned attribute in all metadata
  src/metadata.ts
  test/static/expected metadata without key.xml
  test/static/expected metadata.xml
  test/static/expected_metadata_metadataExtensions.xml
Labels: enhancement

#152 Reduce frequency of dependabot updates
  .github/dependabot.yml
Labels: chore

#151 Remove insecure clockSkew recommendation
  docs/adfs/NameIDFormatError.jpg
  docs/adfs/README.md
  docs/adfs/retrieve_adfs_certificate.sh
Labels: documentation

#162 Update changelog
  .grenrc.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation, dependencies

#161 deps: move express to devDependencies because it is only used in a test.
  package-lock.json
  package.json
Labels: dependencies
