Repository node-saml/node-saml, pull requests merged in 2022-04, with the labels that each got.

#41 Migrate from "should" to "chai"
  package-lock.json
  package.json
  test/crypto.spec.ts
  test/saml-post-signing-tests.spec.ts
  test/samlRequest.spec.ts
  test/samlTests.spec.ts
  test/test-signatures.spec.ts
  test/tests.spec.ts
  test/xml.spec.ts
Labels: chore, dependencies, semver-minor

#44 Upgrade xml-encryption to 2.0.0 (fixes audit issue)
  package-lock.json
  package.json
  test/tests.spec.ts
Labels: dependencies, security

#45 Update packages; bump minimum node to 14
  .github/workflows/workflow.yml
  .mocharc.json
  package-lock.json
  package.json
Labels: dependencies, semver-major

#40 Allow to validate InReponseTo only if provided, to support IDP-initiated login
  README.md
  src/saml.ts
  src/types.ts
  test/tests.spec.ts
Labels: enhancement, breaking-change

#25 Make Audience a required setting
  README.md
  src/saml.ts
  src/types.ts
  test/tests.spec.ts
Labels: enhancement, breaking-change

#61 Make `issuer` required; remove OneLogin default
  src/saml.ts
  test/samlRequest.spec.ts
  test/samlTests.spec.ts
  test/test-signatures.spec.ts
  test/tests.spec.ts
Labels: breaking-change

#63 Stop using import assignments
  test/samlTests.spec.ts
  test/tests.spec.ts
Labels: chore

#64 Remove unused vars
  .eslintrc.json
  test/tests.spec.ts
Labels: chore

#65 Stop using import assignments
  test/crypto.spec.ts
  test/test-signatures.spec.ts
Labels: chore

#66 Saml options typing
  test/crypto.spec.ts
  test/tests.spec.ts
Labels: chore

#60 Correctly reset Sinon fake timers
  package-lock.json
  package.json
  test/tests.spec.ts
Labels: bug

#68 Support Node 18
  .github/workflows/workflow.yml
  test/tests.spec.ts
Labels: chore, dependencies

#69 Clean up exception messages and related tests
  src/saml.ts
  test/tests.spec.ts
Labels: chore

#71 Remove unused request dependency
  package-lock.json
  package.json
Labels: dependencies

#72 Remove unused `qs` types
  package.json
Labels: dependencies

#73 Move dependency types next to dependencies
  package-lock.json
  package.json
Labels: dependencies

#74 Add code coverage
  .eslintignore
  .github/workflows/workflow.yml
  .gitignore
  .nycrc.json
  .prettierignore
  package-lock.json
  package.json
  tsconfig.json
Labels: chore

#75 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#67 Extend available options for NameIDPolicy attributes
  README.md
  src/saml.ts
  src/types.ts
  test/samlRequest.spec.ts
  test/tests.spec.ts
Labels: enhancement

#76 Add codecov and DeepScan badges
  README.md
Labels: documentation

#59 Fix issues with cache provider potentially returning expired keys
  src/inmemory-cache-provider.ts
  test/cache.spec.ts
  test/tests.spec.ts
Labels: bug

#77 Tighten `any` type
  src/passport-saml-types.ts
  test/crypto.spec.ts
  test/samlRequest.spec.ts
  test/tests.spec.ts
  test/types.ts
Labels: chore

#79 Address polynomial regular expression used on uncontrolled data
  src/crypto.ts
Labels: bug, security

#80 Clear up ambiguous branch
  src/saml.ts
Labels: chore
