Repository node-saml/node-saml, pull requests merged in 2022-05, with the labels that each got.

#81 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#43 Support multiple Assertion SubjectConfirmation
  src/saml.ts
  test/static/response.root-signed.message-signed-double-subjectconfirmation.xml
  test/static/response.root-signed.message-signed-empty-subjectconfirmation.xml
  test/static/response.root-signed.message-signed-no-subjectconfirmation.xml
  test/tests.spec.ts
Labels: enhancement

#78 Factor out metadata routines
  src/saml.ts
  src/saml/metadata.ts
  src/types.ts
Labels: chore
