Repository node-saml/node-saml, pull requests merged in 2022-11, with the labels that each got.

#213 Update @xmldom/xmldom
  package-lock.json
  package.json
  src/xml.ts
  test/test-signatures.spec.ts
Labels: dependencies

#210 Fixes #208, updated readme by updating package names.
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: documentation

#219 Lock to TypeScript <4.9.0 due to a regression in 4.9.3
  package.json
Labels: dependencies

#223 Remove pre-release comments from README
  README.md
Labels: documentation

#221 fix: correct handling of XML entities in signature attributes
  src/xml.ts
  test/static/signatures/valid/response.root-signed.assertion-unsigned-13-signature.xml
  test/static/signatures/valid/response.root-signed.assertion-unsigned-xd-signature.xml
  test/test-signatures.spec.ts
Labels: bug
