Repository node-saml/node-saml, pull requests merged in 2023-04, with the labels that each got.

#269 Update minor dependencies
  .grenrc.js
  .markdownlint.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies

#257 Improve audience mismatch error message
  src/saml.ts
  test/tests.spec.ts
Labels: enhancement

#271 Acknowledge that XML can be parsed to `any`
  src/types.ts
Labels: chore

#263 feat: support additionalParams on HTTP-POST binding
  src/saml.ts
  test/samlRequest.spec.ts
Labels: enhancement
