Repository node-saml/node-saml, pull requests merged in 2023-05, with the labels that each got.

#214 Have the default callback URL protocol be https
  README.md
  src/saml.ts
  src/types.ts
  test/cache.spec.ts
  test/samlRequest.spec.ts
  test/samlTests.spec.ts
  test/test-signatures.spec.ts
  test/tests.spec.ts
Labels: breaking-change

#225 Add public key support
  README.md
  src/crypto.ts
  src/metadata.ts
  src/saml.ts
  src/types.ts
  src/xml.ts
  test/crypto.spec.ts
  test/samlTests.spec.ts
  test/test-signatures.spec.ts
  test/tests.spec.ts
  test/types.ts
Labels: enhancement

#226 Remove types specific to Passport
  src/types.ts
Labels: chore

#224 Export types required for SamlOptions
  src/index.ts
  src/passport-saml-types.ts
  src/saml.ts
  src/types.ts
  test/samlTests.spec.ts
Labels: bug, breaking-change
