Repository node-saml/node-saml, pull requests merged in 2024-02, with the labels that each got.

#337 Export generateServiceProviderMetadata
  README.md
  src/constants.ts
  src/index.ts
  src/metadata.ts
  src/saml.ts
  src/types.ts
  test/tests.spec.ts
Labels: enhancement

#343 Rename `cert` to `idpCert` and `signingCert` to `publicCert`
  README.md
  src/index.ts
  src/metadata.ts
  src/saml.ts
  src/types.ts
  test/cache.spec.ts
  test/samlRequest.spec.ts
  test/samlTests.spec.ts
  test/test-signatures.spec.ts
  test/tests.spec.ts
Labels: breaking-change

#36 Added X509 certificate to KeyInfo X509Data, if passed through options
  README.md
  src/types.ts
  src/xml.ts
  test/saml-post-signing-tests.spec.ts
Labels: documentation, enhancement

#344 Update minor dependencies and Node to 18
  package-lock.json
  package.json
Labels: breaking-change, dependencies
